version: "3.9"

services:
  # ================= FRONTEND =================
  frontend:
    build:
      context: ./Front-main
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - product-service
      - order-service
    environment:
      - NODE_ENV=production
    networks:
      - microservices-net

  # ================= AUTH SERVICE =================
  auth-service:
    build:
      context: ./auth-service-main
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
    networks:
      - microservices-net

  # ================= ORDER SERVICE =================
  order-service:
    build:
      context: ./order-service-main
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    networks:
      - microservices-net

  # ================= PRODUCT SERVICE (GO) =================
  product-service:
    build:
      context: ./product-service-main
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "3001:3001"
    networks:
      - microservices-net

  # ================= NGINX =================
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-gateway
    ports:
      - "80:80"
    depends_on:
      - frontend
      - auth-service
      - product-service
      - order-service
    networks:
      - microservices-net

# ================= NETWORK =================
networks:
  microservices-net:
    driver: bridge
